### ISSUE TITLE
carousel makes it difficult to read code samples

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/trypyramid.com#110]
The carousel added in commits a03b98dec8250f22cdc0977fe2af8394f217eb64 and b1d2c9754a44d2a065d17d0bed404ba431519eca make it difficult to read the code samples.

[This site](http://shouldiuseacarousel.com/) pretty much explains my frustration with carousels, especially when they contain only text.

**Comment by blaflamme** [comment]
The visible ones are as easy as before to read, nothing has changed. The full list of examples are taking too much space so until we find a better way to expose them I prefer to keep it that way. Tabs are not great and we also would want to put more there. I don't think the focus should be on them, so if people are interested to see more they'll wait or click on bullets.

The site has an interesting point of view, OTOH I find some of their arguments to be **why** I should use a carousel.

**Comment by cguardia** [comment]
Maybe we can make a click on each example open the respective docs page?

**Comment by cguardia** [comment]
@blaflamme Now that I see it live, I also don't like the carousel too much for the examples, but I agree that they take too much space. However, I still think we need to link to docs or something for each example.

**Comment by blaflamme** [comment]
Sure a reference to the docs would be great. We can have more ui to make it clearer it's a zone with multiple examples or find a better way to present them. But for the purpose of this front page, the `hello world` example is more than enough to me, since this page was initially thought with the following text in mind without any code examples, not even the `hello world` example. I fear we'll reach a point where we miss the initial goal we had in mind, and the work done to make it happen, and try to put too much technical stuff that is not relevant to the pitch level.

As an example the text under Quick Start is great in itself and is great on a technical front page introducing to the docs and pyramid ecosystem. And then you reach the remaining text pitched at an higher level that doesn't connect or contextually relate to what we expressed before. In fact we're trying to merge two different endpoints (audiences) on the same page with two different pitches :(

**Comment by cguardia** [comment]
Right, but still, I think it's infinitely better to have this two audience problem with a super nice looking site, rather than have a nice site for one audience and the pylons project mess for everyone else.

**Comment by blaflamme** [comment]
oh yeah sure... And I don't think we should delegate that to the Pylons site too, it'll be again a lot confusing.

**Comment by stevepiercy** [comment]
As far as the snippets on the home page of trypyramid.com, are we in agreement on the following?

1. we need snippets
1. we need to add links from the snippet description to relevant pages in the docs
1. we don't like the carousel

FWIW, in the open PRs, I've started to pull Pyramid-specific pages out of pylonsproject.org and move them over to trypyramid.com.

Also keep in mind we have three major marketing-releated redesigns in the works:

* https://github.com/Pylons/trypyramid.com
* https://github.com/Pylons/pylonsproject.org (was https://github.com/Pylons/pylonshq and https://github.com/Pylons/pylonsrtd)
* https://github.com/Pylons/pyramid-sphinx-themes (our new Sphinx theme for Pyramid)

**Comment by blaflamme** [comment]
If we're about to agree to remove the carousel and that each snippets are visible, and taking far too much space, we'll have to push them at the end after the «marketed» text that in my opinion matter most on this page than the snippets.

**Comment by stevepiercy** [comment]
I am 100% in favor of showing the snippets in something that does not slide around.

So where should the snippets be placed? Immediately above the footer? Between which two `<section>`s?

BTW, have I mentioned I hate carousels? 😛
