### ISSUE TITLE
I don't understand this bullet point

### ISSUE THREAD

**Issue by ronnix** [Pylons/trypyramid.com#237]
In the "Start small" section, I don't understand this bullet point:

- *Tap into a variety of high-quality evaluator and advanced developer documentation*

**Comment by stevepiercy** [comment]
Since I would have to explain it, it does not achieve the desired result. I think we missed the mark by not defining what is an "evaluator". The intent was to define the people who decide which technology to use by evaluating it, such as CTOs.

I'd appreciate any improvement you can suggest. I think two concepts and two target audiences should yield two bullet points, rather than combing them into one.

**Comment by ronnix** [comment]
Oh, so it means there's high quality documentation both for developers and for people evaluating the technology.

I had trouble parsing the sentence, and had no idea what an evaluator was in that context.

That second point feels a bit meta: as a CTO reading that page to evaluate Pyramid, you read that it has great documentation for you to evaluate. Show, don't tell?

**Comment by stevepiercy** [comment]
How does this sound?

"Tap into a variety of **high-quality documentation** for evaluating, trying out, or doing advanced development with Pyramid"

This removes the subject of *who you are* and instead shifts it to *what you do*.

As an aside, when writing copy for marketing, I often get lost in concepts and lose sight of the intended audience. I appreciate a fresh perspective.

**Comment by ronnix** [comment]
:+1:
