### ISSUE TITLE
GitHub, Twitter, etc. badges

### ISSUE THREAD

**Issue by pauleveritt** [Pylons/trypyramid.com#8]
Add these in the "right" place.
- [x] 1. Decide which Twitter handle to use. Options include the following.
  @Pylons
  @trypyramid
  @usepyramid
  @pyramidweb
  @pyramidwebapp
  @pyramidapp
  @other
- [x] 2. [Twitter brand assets and guidelines](https://about.twitter.com/press/brand-assets).
- [ ] 3. [GitHub icon usage guidelines](https://help.github.com/articles/using-an-octocat-to-link-to-github-or-your-github-profile/). We should use the Mark.
- [ ] 4. [Read the Docs badges](http://docs.readthedocs.org/en/latest/badges.html)
- [ ] 5. [Read the Docs brand usage guidelines](https://github.com/rtfd/readthedocs.org/issues/425)
- [x] 6. [Google Groups](https://groups.google.com/forum/#!forum/pylons-discuss).
- [x] 7. [IRC #pyramid on freenode.net](irc://irc.freenode.net:6667/pyramid) or using [webchat](https://webchat.freenode.net/?channels=%23pyramid&uio=d4).

**Comment by stevepiercy** [comment]
1. Decide which Twitter handle to use. Options include the following.
@Pylons
@trypyramid
@usepyramid
@pyramidweb
@other

2. [Twitter brand assets and guidelines](https://about.twitter.com/press/brand-assets).

3. [GitHub icon usage guidelines](https://help.github.com/articles/using-an-octocat-to-link-to-github-or-your-github-profile/). We should use the Mark.

4. [Read the Docs badges](http://docs.readthedocs.org/en/latest/badges.html)

5. [Read the Docs brand usage guidelines](https://github.com/rtfd/readthedocs.org/issues/425)

6. [Google Groups](https://groups.google.com/forum/#!forum/pylons-discuss). I'm unsure of this one because of its name, but I guess that's a larger discussion. So for now, perhaps a generic [discussion icon](https://duckduckgo.com/?q=icon+discussion&ia=images) or [mail list icon](https://duckduckgo.com/?q=icon+email&ia=images)

7. [IRC #pyramid on freenode.net](irc://irc.freenode.net:6667/pyramid) or using [IRC.lc](http://irc.lc/freenode/pyramid/).

**Comment by stevepiercy** [comment]
@trypyramid https://github.com/stevepiercy/trypyramid.com/commit/466e55a8c5552b42c7d0a46b2d5015de14558751

**Comment by stevepiercy** [comment]
Google Groups in PR #119

**Comment by stevepiercy** [comment]
Twitter follow button added to site and added in Media Feeds in #224.

**Comment by stevepiercy** [comment]
I have no idea what we would want to do with GitHub or RTD at this point. I'm closing this issue, but feel free to reopen it with further direction.
